### ISSUE TITLE
MUM2021

### ISSUE THREAD

**Issue by tenhishadow** [AntonAndreevichMoroz/RealMikrotikBackup#1]
@AntonAndreevichMoroz 
please check
https://github.com/tenhishadow/mbkp

там проще и структура нормальная

**Comment by AntonAndreevichMoroz** [comment]
Приветствую.
Проще - вопрос спорный. Если отдать первичную настройку первой линии по вашему скрипту, то боюсь возникнет больше вопросов.
Контроль - не увидел в вашем варианте механизмов контроля прошел ли бекап удачно или с ошибкой. Точнее логи то есть, но их надо вручную контролировать? Т.е. дополнительные телодвижения.
Управлять списком устройств сложнее учитывая, что необходимо под каждое устройство делать свой конфиг файл и отдельное задание крон.
Про структуру если честно не понял, что вы имели ввиду. +- методы и структура одинаковые.
Применение разное. В вашем варианте может быть проще и удобнее на не большом парке устройств, скажем до 10 штук. Далее на мой взгляд будут появляться затруднения в контроле.
Плюс к этому ваш вариант менее функциональный и меньше перспектив на развитие.
Но думаю каждый останется при своем мнении)

**Comment by tenhishadow** [comment]
@AntonAndreevichMoroz 

> Проще - вопрос спорный. Если отдать первичную настройку первой линии по вашему скрипту, то боюсь возникнет больше вопросов.

Первой линии? Настройку бэкапов? Я понимаю, что это Россия и первая линия там часто делает всё( потому что сам так работал ), но из того, что она именно "первая", она по определению только пользователей поддерживает и доступа к бэкапам не имеет.


> Контроль - не увидел в вашем варианте механизмов контроля прошел ли бекап удачно или с ошибкой. Точнее логи то есть, но их надо вручную контролировать? Т.е. дополнительные телодвижения.

Ну логи есть, да. Простой Zabbix замечательно справляется с этим, и, что самое главное - алерты присылает по правилам заббикса, т.е. делает...мониторинг...в системе...для мониторинга

> Применение разное. В вашем варианте может быть проще и удобнее на не большом парке устройств, скажем до 10 штук. Далее на мой взгляд будут появляться затруднения в контроле.

настройка хостов у меня предполагается через стандартные средства - конфиг ssh для хоста. Т.е. можно даже дефолты написать и всё будет. Проблемы с контролем? Ну я работал на проектах с RHEL и AIX и имея простой конфиг ssh можно было управлять 10000 хостов. Вообще без проблем и даже никакая тут не нужна была. Потому что это просто конфиги ssh или один общий с дефолтным юзером и параметрами. ```man ssh_config```


> Плюс к этому ваш вариант менее функциональный и меньше перспектив на развитие.

да ровно столько же, у меня ещё и export config шифруется через openssh и не лежит как plaintext на файловой системе. А в гит запихать 3 команды. Web-ui? ну вроде и да, но выбор php адекватных людей сразу оттолкнёт, да и сам UI нужен ли? Особенно забавно добавлять хосты каким-то странным образом. 


@AntonAndreevichMoroz да, каждый останется при своём мнении, бесспорно. Я просто хотел показать, что такое уже есть и вы даже не второй и не третий. + скрипты bash просто почекайте через shellcheck. Если создаёте issue для себя что-то заимплементить - делайте PR. https://lab.github.com/ - очень советую пройти
