### ISSUE TITLE
Множественная авторизация

### ISSUE THREAD

**Issue by bolgov0zero** [AntonAndreevichMoroz/RealMikrotikBackup#10]
При выполнении планового/ручного резервного копирования на устройстве происходит множественная авторизация.
Чтобы сделать две РК(экспорт и бинарный) система авторизуется на mikrotik порядка 5 раз. Так и должно быть?

**Comment by AntonAndreevichMoroz** [comment]
Добрый день. Так и должно быть. Если включены оба бекапа, то на каждый по 3 подключения. Есть вариант частично снизить количество подключений при таком сценарии, но это не приоритетная задача для доработки. По возможности внедрим
