### ISSUE TITLE
Статус BAD

### ISSUE THREAD

**Issue by Sniksss** [AntonAndreevichMoroz/RealMikrotikBackup#11]
Установил RMB, подключил одно устройство. Проверил подключение - успешно. Запустил ручной бэкап - успешно, бэкап создался, комит в гит прилетел. Запустил задание по крону, задание успешно. Далее добавил еще одно устройство, проверяю тест подключения, проходит, но бэкап статус - BAD. Проверяю первое созданное устройство, тоже статус BAD. Удалил папку RMB, скачал заново, переконфигурировал, добавил первое устройство, статус подключения -Успешно, но бэкапы снова BAD . Подскажите куда копать, есть ли какие-то логи ?

**Comment by AntonAndreevichMoroz** [comment]
Отправка системных ошибок включается парамметрами
ERROR_NOTIFICATION_TELEGRAM или ERROR_NOTIFICATION_EMAIL
Для отправки нужно также указать настройки телеграм бота или настроек smtp.
Подробнее о настройках https://github.com/AntonAndreevichMoroz/RealMikrotikBackup/wiki/%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B

Перезапуск в расширенном режиме docker-compose stop && docker-compose -f docker-compose-advanced.yml up -d

После запуска можно зайти на http://%ip_address%:5678 и либо вручную запустить workflow бекапа, либо посмотреть ранее запцщенные процессы и визуально посмотреть где ошибка.

Совсем недавно N8N выпустила обновления, которые позволят нормально получать ошибки в веб интерфейс, планирую в ближайшие несколько недель внести обновления, чтобы процесс дебага был удобнее и проще.

**Comment by Sniksss** [comment]
Получил такую ошибку :
Expression 
 /system backup save{{ $env.MK_BACKUP_ENCRYPT_PASSWORD ? " dont-encrypt=no encryption=aes-sha256" : " dont-encrypt=yes"}} name={{$node["Start"].json["filenameonmikrotik"]}}{{ $env.MK_BACKUP_ENCRYPT_PASSWORD ? " password=" +  $env.MK_BACKUP_ENCRYPT_PASSWORD : ""}}

 Result
/system backup save dont-encrypt=yes name=[not found]

**Comment by Sniksss** [comment]
Нашел ошибку, в имени не должно быть пробелов
