### ISSUE TITLE
backups do not work for routeros version 7.3.1

### ISSUE THREAD

**Issue by naem53** [AntonAndreevichMoroz/RealMikrotikBackup#12]
Добрый день!

Подскажите, есть ли в планах доработать проект в части добавления возможности съёма бэкапов с routeros версии 7.х.х?

**Comment by AntonAndreevichMoroz** [comment]
А что у вас не получается в 7.3.1? Я только на long-term тестировал. У нас есть устройства на 7.1.5 и бекапятся они нормально. В changelog я не заметил чего-то что могло бы сломать текущий процесс.

**Comment by naem53** [comment]
Всё в порядке, разобрался. Бэкапы, на версии 7.3.1 проходят успешно.
