### ISSUE TITLE
ROS 7 - export sensitive

### ISSUE THREAD

**Issue by volksem** [AntonAndreevichMoroz/RealMikrotikBackup#15]
Перевел несколько микротиков на ROS 7.4.1 и заметил, что в экспортном бэкапе отсутствуют пароли.
Оказалось, mikrotik переосмыслили подход и в ROS 7 при выполнении команды export пароли не сохраняются в файл, нужно использовать параметр show-sensitive. В ROS 6 наоборот: по умолчанию пароли экспортируются, а чтобы их скрыть нужно использовать параметр hide-sensitive.

**Comment by AntonAndreevichMoroz** [comment]
Очень хорошее замечание. Я сейчас прохожу обучение и времени пока нет. В конце недели поставлю себе в план решить эту проблему и обновить процесс создания бекапов

**Comment by AntonAndreevichMoroz** [comment]
Добавлено изменение в команду создания экспорта. Теперь учитывается версия RouterOS
