### ISSUE TITLE
При обновлении возникает ошибка

### ISSUE THREAD

**Issue by eopens** [AntonAndreevichMoroz/RealMikrotikBackup#17]
Запуская скрипт обновления sudo sh update.sh и получаю ошибку:
update.sh: 9: Syntax error: Bad for loop variable
Как исправить?

**Comment by AntonAndreevichMoroz** [comment]
Добрый день. Это цикл для оформления вывода в рамку. Что у вас за дистрибутив ОС?
Попробуйте или выполнить команды вручную или удалить строки про border из скрипта и перезапустить. Строки под номерами 4-18, 41, 50, 54, 63

**Comment by eopens** [comment]
> Добрый день. Это цикл для оформления вывода в рамку. Что у вас за дистрибутив ОС? Попробуйте или выполнить команды вручную или удалить строки про border из скрипта и перезапустить. Строки под номерами 4-18, 41, 50, 54, 63

Использую Debian 11. Выполнил команды по отдельности, обновление установилось. Спасибо!
