### ISSUE TITLE
Смена пароля скриптом webadminchange.sh

### ISSUE THREAD

**Issue by volksem** [AntonAndreevichMoroz/RealMikrotikBackup#18]
Здравствуйте!
Попытался сменить пароль скриптом webadminchange.sh - получил ошибку, что невозможно найти файл app/models/User.php

В строке 14 прописал полный путь размещения User.php (**RMB_folder**/app/models/User.php) и скрипт успешно отработал.

**Comment by AntonAndreevichMoroz** [comment]
Добрый день. Скорее всего скрипт запускали не из корневой папки RMB, поэтому относительный путь ссылался не туда.

**Comment by volksem** [comment]
Тоже верно! Спасибо =)
