### ISSUE TITLE
Увеличивается размер файла database.sqlite

### ISSUE THREAD

**Issue by imaxiss** [AntonAndreevichMoroz/RealMikrotikBackup#19]
Добрый день, подскажите в чем может быть проблема
Ubuntu 20.04.5 LTS, установлено только RealMikrotikBackup
Добавлено 2 десятка микротиков, при этом постоянно увеличивается размер базы /n8n/data/database.sqlite, за месяц достиг почти 4гб
Файл env по дефолту без git
CRON_START=0 0 3 15,30 * *

**Comment by AntonAndreevichMoroz** [comment]
Это скорее всего данные о запусках, можно сказать что логи выполнения. Вы можете либо просто удалить его предварительно остановив контейнеры. База пересоздается автоматически.
```
docker-compose stop
rm /n8n/data/database.sqlite
docker-compose start
```
Либо если вам не нужны эти логи, то просто их отключить через advenced режим зайдя на адрес http://server:5678/ и в каждой workflow в настройках отключить сохранение предыдущих исполнений.
![image](https://user-images.githubusercontent.com/51225180/201921420-a369e6c9-6a7c-4b27-acb1-c4e8b2e532b3.png)

**Comment by imaxiss** [comment]
Спасибо, действительно это были логи опроса о статусе бэкапа заббиксом
