### ISSUE TITLE
Создать расписание

### ISSUE THREAD

**Issue by Kostyuk-Ruslan** [AntonAndreevichMoroz/RealMikrotikBackup#2]
Было бы здорово прикрутить расписание для бэкапов, для тех кто не будет пользоваться git

**Comment by AntonAndreevichMoroz** [comment]
Приветствую. Расписание вы можете создать вне зависимости от использования git. Даже больше, оно работает из коробки. По умолчанию в 21:00 происходит удаление старых записей, в 22:00 процнсс резервного копирования запускается.
А использование git включается отдельными настройками. И его использование по умолчанию отключено.
Подробнее о настройках можно почитать здесь https://github.com/AntonAndreevichMoroz/RealMikrotikBackup/wiki/%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B
Просьба закрыть данное обращение если я ответил на ваш вопрос или уточнить, что вы хотите реализовать.

**Comment by Kostyuk-Ruslan** [comment]
а как я сам могу создать или изменить расписание, подскажите где я могу это настроить ?

**Comment by AntonAndreevichMoroz** [comment]
Вам необходимо указать параметры в файле .env в корне проекта. Подробнее в описании по ссылке что я указал выше

**Comment by Kostyuk-Ruslan** [comment]
Точно ! Все понял, спасибо большое ! закрываю

**Comment by KirsaNKayfat** [comment]
Добрый день!

Настроен гит.

По расписанию экспортные бэкапы сливаются на гит.

Вопрос, должны ли бэкапы сливаться на гит моментально сразу после того как в ручную запустить выполнения бэкапа?
