### ISSUE TITLE
Не создаются и не загружаются экспортные бекпы

### ISSUE THREAD

**Issue by nopsss** [AntonAndreevichMoroz/RealMikrotikBackup#20]
Доброго дня. 
Бинарные капы создаются без проблем, а вот экспортные ни в какую. Куда смотреть даже не представляю.
Подскажите что я делаю не так.

**Comment by AntonAndreevichMoroz** [comment]
Добрый день. Если это происходит на chr, то обновитесь. Это уже исправлено.

**Comment by nopsss** [comment]
> Добрый день. Если это происходит на chr, то обновитесь. Это уже исправлено.

Спасибо, так и поступил, стали создаваться. Но сейчас не получается выгрузить в git.
Пока разбираюсь. Все настройки указал вроде верно, ссылку на гитхаб как в вики, логин=адрес электронки, пароль, юзернейм и почту от аккаунта... Но не появляются.... Возможно я что-то забыл.

**Comment by nopsss** [comment]
нашел причину. 
remote: Support for password authentication was removed on August 13, 2021.
Github более не позволяет авторизовываться по паролю:(
Создаем токен и все взлетает
