### ISSUE TITLE
Последний статус

### ISSUE THREAD

**Issue by alotofgold** [AntonAndreevichMoroz/RealMikrotikBackup#4]
Запустил RMB. Все работает, но не отображаются Последний статус, Последняя удачная попытка и Последняя попытка с ошибкой. Как поправить?
Спасибо.

**Comment by AntonAndreevichMoroz** [comment]
Покажите скрин просмотра устройства.
Тест подключения проходит?
Файлы бекапа появляются?

**Comment by alotofgold** [comment]
Тест проходит.
Файлы бекапа появляются.
![image](https://user-images.githubusercontent.com/22495007/148892069-36bc355b-0ff2-490a-a3a6-d4338f60e1d2.png)

**Comment by eopens** [comment]
Аналогичная проблема, но статус у меня пишет BAD, хотя тест проходит и файлы бекапа появляются!

**Comment by ilyadavydyuk** [comment]
> Аналогичная проблема, но статус у меня пишет BAD, хотя тест проходит и файлы бекапа появляются!

запустите 
`docker-compose down && docker-compose -f docker-compose-advanced.yml up -d`
после зайдите на 
`http://%ip_address%:5678`
откройте очередь процессов, и запустите бекап из основного интерфейса.
Посмотрите в процессах, где именно ошибка.

**Comment by AntonAndreevichMoroz** [comment]
Добрый день. Самое простое либо настроить отправку системных ошибок на почту или в телеграмм. Либо запустить через advanced режим и посмотреть в вебе на порту 5678 в интерфейсе N8N как проходит процесс. (Спасибо @ilyadavydyuk за подробное описание как это сделать)

Я сейчас с большой нагрузкой по задачам, постараюсь процесс дебага более подробно описать к понедельнику-вторнику.

Отправка системных ошибок включается парамметрами
ERROR_NOTIFICATION_TELEGRAM или ERROR_NOTIFICATION_EMAIL
Для отправки нужно также указать настройки телеграм бота или настроек smtp.
Подробнее о настройках https://github.com/AntonAndreevichMoroz/RealMikrotikBackup/wiki/%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B

**Comment by alotofgold** [comment]
В моем случае проблема решена. В настройках стояло использовать GIT, но GIT настроен еще не был. Отключил и статус начал отображаться. Спасибо.
