### ISSUE TITLE
При запросе на бэкап никаких действий на Микроте нет

### ISSUE THREAD

**Issue by macmanDevOps** [AntonAndreevichMoroz/RealMikrotikBackup#6]
Добрый день,
Хотел бы внедрить RMB себе, но столкнулся с проблемой. Тест на подключение проходит, но при запросе на бэкап никаких действий на микроте нет. Подскажите в какую сторону стоит посмотреть?
![image](https://user-images.githubusercontent.com/74489984/149992316-beafd9be-aa63-413d-833c-619f0533ba2c.png)

**Comment by AntonAndreevichMoroz** [comment]
Добрый день. Самое простое либо настроить отправку системных ошибок на почту или в телеграмм. Либо запустить через advanced режим и посмотреть в вебе на порту 5678 в интерфейсе N8N как проходит процесс.

Я сейчас с большой нагрузкой по задачам, постараюсь процесс дебага более подробно описать к понедельнику-вторнику.

**Comment by AntonAndreevichMoroz** [comment]
Отправка системных ошибок включается парамметрами
ERROR_NOTIFICATION_TELEGRAM или ERROR_NOTIFICATION_EMAIL
Для отправки нужно также указать настройки телеграм бота или настроек smtp.
Подробнее о настройках https://github.com/AntonAndreevichMoroz/RealMikrotikBackup/wiki/%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B9%D0%BA%D0%B0-%D1%81%D0%B8%D1%81%D1%82%D0%B5%D0%BC%D1%8B

Перезапуск в расширенном режиме docker-compose stop && docker-compose -f docker-compose-advanced.yml up -d

После запуска можно зайти на http://%ip_address%:5678 и либо вручную запустить workflow бекапа, либо посмотреть ранее запцщенные процессы

**Comment by macmanDevOps** [comment]
Добрый вечер,
Проблему удалось решить. Как оказалось, при создании бэкапа, за основу берется имя указанное в поле "Имя".
У меня в имени имеются знаки "()" наличие которых cli микрота не воспринимал. После смены имени, все работает.
Спасибо за ответ
