### ISSUE TITLE
Ошибка в Wiki

### ISSUE THREAD

**Issue by volksem** [AntonAndreevichMoroz/RealMikrotikBackup#7]
Вероятно, в Wiki закралась ошибка в части описания переменных CRON_START и CRON_PURGE_START.
_0 0 22 * * *_ - это не "_Каждый день в 22:00_", это _Каждый 22 день месяца в 00:00_, т.к. расширенный формат CRON выглядит так: _<Минуты> <Часы> <Дни_месяца> <Месяцы> <Дни_недели> <Годы>_
Скорее всего, пример должен быть таким: _0 22 * * * *_

**Comment by AntonAndreevichMoroz** [comment]
Нет, ошибки нет. Вот документация по N8N. Они используют формат именно с секундами, а не с годами. Но как указывается формат иожет быть более привысный без указания секунд и это тоже должно работать.
https://docs.n8n.io/nodes/n8n-nodes-base.cron/#node-reference

**Comment by volksem** [comment]
Понял, благодарю!
